export const EMAILS = [
  {
    id: 1,
    sender: "promo@buythis.com",
    subject: "Exclusive offer just for you!",
    body: "Buy our amazing product at 90% off! Limited time only!",
  },
  {
    id: 2,
    sender: "colleague@work.com",
    subject: "Project update",
    body: "Hey, just updating you on the latest project status...",
  },
  {
    id: 3,
    sender: "news@randomtech.io",
    subject: "New AI tool just launched!",
    body: "Boost productivity with our latest AI-based writing assistant.",
  },
  {
    id: 4,
    sender: "recruiter@jobsnow.com",
    subject: "Exciting job opportunity at FinTechCorp",
    body: "We came across your resume and would love to speak with you.",
  },
  {
    id: 5,
    sender: "support@webhostplus.com",
    subject: "Invoice Due for Web Hosting",
    body: "Your monthly invoice is ready. Please make a payment by May 5.",
  },
  {
    id: 6,
    sender: "offers@flyaway.com",
    subject: "Summer deals on flights!",
    body: "Fly round-trip for as low as $99. Book your vacation today!",
  },
  {
    id: 7,
    sender: "notifications@banksecure.com",
    subject: "Important: Login attempt detected",
    body: "A login attempt was made from a new device. Was this you?",
  },
  {
    id: 8,
    sender: "events@meetup.io",
    subject: "You're invited: AI Enthusiasts Monthly Meetup",
    body: "Join us this Friday at 6PM for talks and networking.",
  },
  {
    id: 9,
    sender: "spammy@bargainhunter.biz",
    subject: "Cheap meds without prescription",
    body: "Order today and save 80% on your next prescription refill!",
  },
  {
    id: 10,
    sender: "updates@linkedin.com",
    subject: "5 new profile views this week",
    body: "See who's been looking at your LinkedIn profile.",
  },
  {
    id: 11,
    sender: "noreply@streamflix.com",
    subject: "Your subscription will renew soon",
    body: "Your Streamflix plan will renew on May 7 for $12.99/month.",
  },
  {
    id: 12,
    sender: "sales@quickbuildtools.com",
    subject: "Limited-time deal for developers!",
    body: "Get our build tools suite at 60% off, this week only.",
  },
  {
    id: 13,
    sender: "prof.smith@university.edu",
    subject: "Meeting rescheduled",
    body: "Our meeting has been moved to Thursday at 3 PM.",
  },
  {
    id: 14,
    sender: "hr@startupx.com",
    subject: "Interview Feedback",
    body: "Thank you for taking the time to interview with us. We’ll be in touch.",
  },
  {
    id: 15,
    sender: "alerts@cloudsync.com",
    subject: "New device signed in",
    body: "A device in New York just signed in to your account.",
  },
  {
    id: 16,
    sender: "promo@spameasydealz.net",
    subject: "You won a free iPhone!",
    body: "Click here to claim your free iPhone before the offer expires!",
  },
  {
    id: 17,
    sender: "amy@family.com",
    subject: "Dinner plans?",
    body: "Want to do pizza this Friday? Let me know what works for you.",
  },
  {
    id: 18,
    sender: "updates@github.com",
    subject: "New comment on issue #42",
    body: "Someone commented on an issue you're subscribed to.",
  },
  {
    id: 19,
    sender: "contact@smallbizsolutions.co",
    subject: "Grow your business with SEO tools",
    body: "Discover how our tools can help increase your traffic by 300%.",
  },
  {
    id: 20,
    sender: "calendar@google.com",
    subject: "Upcoming event: Team Sync",
    body: "Reminder: Team Sync is scheduled for Friday at 10:00 AM.",
  },
];
